name: quill_native_bridge
description: "An internal Flutter plugin for flutter_quill package to access platform-specific APIs"
version: 11.0.0
homepage: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge
repository: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge
issue_tracker: https://github.com/FlutterQuill/quill-native-bridge/issues
documentation: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge
topics: [clipboard, os-integration, quill-native-bridge, quill, flutter-quill]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  quill_native_bridge_android: ^0.0.1
  quill_native_bridge_platform_interface: ^0.0.1
  quill_native_bridge_windows: ^0.0.1
  quill_native_bridge_linux: ^0.0.1
  quill_native_bridge_ios: ^0.0.1
  quill_native_bridge_macos: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        default_package: quill_native_bridge_android
      ios:
        default_package: quill_native_bridge_ios
      macos:
        default_package: quill_native_bridge_macos
      windows:
        default_package: quill_native_bridge_windows
      linux:
        default_package: quill_native_bridge_linux